---
- name: install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - bash
    - bash-completion

- name: copy system-wide profile
  template:
    src: etc_profile.d_Z00-xdg.sh.j2
    dest: /etc/profile.d/Z00-xdg.sh
    owner: root
    group: root
    mode: 0644

- set_fact:
    bashrc_path: /etc/bash.bashrc
  when: ansible_distribution == "Debian"

- set_fact:
    bashrc_path: /etc/bashrc
  when: ansible_distribution == "Fedora"

- name: copy system-wide bashrc
  copy:
    src: etc_bash.bashrc
    dest: "{{ bashrc_path }}"
    owner: root
    group: root
    mode: 0644
